parent: classic
name: yarntheme
display_name: Yarnstreet.com Theme
author:
  name: Kubek z Twoim Nadrukiem
version: 1.0.0
assets:
  use_parent_assets: true
  css:
    all:
      - id: owl_css
        path: assets/css/owl.carousel.min.css
        media: all
        priority: 100
      - id: own_theme
        path: assets/css/owl.theme.default.min.css
        media: all
        priority: 100
  js:
    all:
      - id: jquery_min
        path: assets/js/jquery.min.js
        priority: 200
      - id: owl_js
        path: assets/js/owl.carousel.min.js
        priority: 200
