services:
  prestashop:
    image: aegiru/nadruk-prestashop:latest
    ports:
      - 18875:443
    environment:
      DB_SERVER: admin-mysql_db
      DB_NAME: BE_188752
      DB_USER: root
      DB_PASSWD: student
      PS_INSTALL_AUTO: 1
      MEMCACHED_SERVER: memcached
    networks:
      - admin-mysql_default
      - nadruk_prestashop
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
  memcached:
    image: memcached:latest
    networks:
      - nadruk_prestashop
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

networks:
  nadruk_prestashop:
  admin-mysql_default:
    external: true